server:
  port: 8888

spring:
  servlet:
    multipart:
      enabled: true
      # 单个文件的最大上限
      max-file-size: 1000MB
      # 单个请求的文件总大小上限
      max-request-size: 1000MB
  mvc:
    pathmatch:
      # 解决swagger3的报错问题
      matching-strategy: ant_path_matcher
  thymeleaf:
    # html存放的具体路径，可进行自定义，示例：resources/templates
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  data:
    # milvus矢量数据库连接信息
    milvus:
      host: MY-SERVER
      port: 19530
    # mongo连接信息
    mongodb:
      uri: mongodb://guoyr:guoyr%402021@MY-SERVER:27017/admin
      database: guoyr
      option:
        min-connection-per-host: 0
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-wait-time: 12000
        max-connection-idle-time: 0
        max-connection-life-time: 0
        connect-timeout: 0
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15


# 文件上传后的存储路劲
uploadFile:
#  tempLocation: /Users/admin/Documents/idea/code/milvus-actual/img
  tempLocation: D:\IdeaProjects\milvus-actual\img

# ai引擎
engine:
  # 虹软
  arcSoft:
    appId: APRt68C3sT6X2TfJpgSZv4NszZC7YRTewxtv4gqstAeS
    sdkKey: AxL7CDAZqt19Z1zayyVdS61KkP7THhCfjQewqmR3bfZY
    lib: D:\IdeaProjects\milvus-actual\src\main\resources\lib\WIN64
    testImgOne: D:\IdeaProjects\milvus-actual\src\main\resources\img\1.jpg
    testImgTwo: D:\IdeaProjects\milvus-actual\src\main\resources\img\4.jpg

