server:
  port: 8888




database:
  milvus:
    host: 124.221.237.254
    port: 19530

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


uploadFile:
  tempLocation: /Users/admin/Documents/idea/code/milvus-actual/img
engine:
  # 虹软
  arcSoft:
    appId: APRt68C3sT6X2TfJpgSZv4NszZC7YRTewxtv4gqstAeS
    sdkKey: AxL7CDAZqt19Z1zayyVdS61KkP7THhCfjQewqmR3bfZY
    lib: D:\IdeaProjects\milvus-actual\src\main\resources\lib\WIN64
    testImgOne: D:\IdeaProjects\milvus-actual\src\main\resources\img\1.jpg
    testImgTwo: D:\IdeaProjects\milvus-actual\src\main\resources\img\4.jpg
